domains: "stg-storymap.knightlab.com"
cnames: "storymap.knilab.com storymapjs.knilab.com"

init_env_stg:
  CDN_URL: "//cdn.knightlab.com/libs/storymapjs/dev/"

init_env: "{{ init_env_common|combine(init_env_stg) }}"
service_exec: "{{ virtualenv}}/bin/gunicorn -b :{{ service_port }} --workers 1 --reload {{ wsgi_application }}"

s3_src_dir: "../dist" # relative to deploy dir
s3_dest: s3://cdn.knightlab.com/libs/storymapjs/dev/
