- hosts: 127.0.0.1
  connection: local
  vars_files:
    - "{{ config_dir }}/config.common.yml"
    - "{{ config_dir }}/config.{{ env }}.yml"
    - "{{ vault }}"
  gather_facts: false

  pre_tasks:


    # warn False on these tasks b/c we are calling git directly. Be on the
    # lookout for updates to the git module that will allow us to replace
    # some of these shell calls

    - name: "get current working branch"
      shell: git rev-parse --abbrev-ref HEAD
      args:
        chdir: "{{ project_root }}"
        warn: False
      register: original_branch

    - name: "checkout deployment branch: {{ project_version }}"
      shell: git checkout {{ project_version }}
      args:
        chdir: "{{ project_root }}"
        warn: False

    # Don't use the git module here - it will overwrite local commits.
    # See: https://github.com/ansible/ansible-modules-core/issues/614
    # Does not seem to work with tags
    #- name: "sync local deployment branch: {{ project_version }}"
    #  shell: git pull; git push
    #  args:
    #    chdir: "{{ project_root }}"
    #    warn: False

    - name: "build distribution"
      shell: npx webpack -c webpack.{{ env }}.js
      args:
        chdir: "{{ project_root }}"


  roles:

    - role: knightlab
    - role: s3


  post_tasks:

    - name: "checkout original branch: {{ original_branch.stdout }}"
      shell: git checkout {{ original_branch.stdout }}
      args:
        chdir: "{{ project_root }}"
        warn: False
